#!/usr/bin/perl
package GmailNotifier;
use Moose;
use AnyEvent;
use AnyEvent::Gmail::Feed;

with 'MooseX::Getopt';

has 'username' => (is => 'rw', isa => 'Str', required => 1);
has 'password' => (is => 'rw', isa => 'Str', required => 1);
has 'interval' => (is => 'rw', isa => 'Int', default  => 60);

sub run {
    my ($self, %args) = @_;

    my %seen;
    AnyEvent::Gmail::Feed->new(
        username => $self->username,
        password => $self->password,
        interval => $self->interval,
        on_new_entry => sub {
            my $entry = shift;
            ## you can send notify with Growl, Notify-OSD or whatever
            warn "send notify: " . $entry->summary;
        },
    );
    AnyEvent->condvar->recv;
}

package main;
GmailNotifier->new_with_options->run;
